services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=parking_db'
      - 'MYSQL_PASSWORD=parking'
      - 'MYSQL_ROOT_PASSWORD=parking'
      - 'MYSQL_USER=parking'
    ports:
      - '3306'
